### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by moquette** [jackw/repo-copy-webpack-plugin-pnp#1]
Good morning.

Looking for a possible fix for running copy-webpack-plugin w/Yarn pnp, I came across your repo.  However, I was unable to get it to build.  Any thoughts?

[ ~/Downloads/repo-copy-webpack-plugin-pnp-main/ ] $ yarn
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: Done with warnings in 0s 92ms

[ ~/Downloads/repo-copy-webpack-plugin-pnp-main/ ] $ yarn build
[webpack-cli] HookWebpackError: Cannot find package 'globby' imported from /Users/moquette/Downloads/repo-copy-webpack-plugin-pnp-main/.yarn/__virtual__/copy-webpack-plugin-virtual-1a86820edc/0/cache/copy-webpack-plugin-npm-10.0.0-cbf3ed64fd-70652af613.zip/node_modules/copy-webpack-plugin/dist/index.js
Did you mean to import globby-npm-12.0.2-6be2a4aac6-f474ced866.zip/node_modules/globby/index.js?
    at makeWebpackError (/Users/moquette/Downloads/repo-copy-webpack-plugin-pnp-main/.yarn/__virtual__/webpack-virtual-6c5f2d62d7/0/cache/webpack-npm-5.64.1-77fbd9ac18-d2a1baddae.zip/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /Users/moquette/Downloads/repo-copy-webpack-plugin-pnp-main/.yarn/__virtual__/webpack-virtual-6c5f2d62d7/0/cache/webpack-npm-5.64.1-77fbd9ac18-d2a1baddae.zip/node_modules/webpack/lib/Compilation.js:3055:12
    at eval (eval at create (/Users/moquette/Downloads/repo-copy-webpack-plugin-pnp-main/.yarn/cache/tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:51:1)
    at /Users/moquette/Downloads/repo-copy-webpack-plugin-pnp-main/.yarn/__virtual__/webpack-virtual-6c5f2d62d7/0/cache/webpack-npm-5.64.1-77fbd9ac18-d2a1baddae.zip/node_modules/webpack/lib/Compilation.js:508:26
    at /Users/moquette/Downloads/repo-copy-webpack-plugin-pnp-main/.yarn/__virtual__/copy-webpack-plugin-virtual-1a86820edc/0/cache/copy-webpack-plugin-npm-10.0.0-cbf3ed64fd-70652af613.zip/node_modules/copy-webpack-plugin/dist/index.js:485:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
-- inner error --
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'globby' imported from /Users/moquette/Downloads/repo-copy-webpack-plugin-pnp-main/.yarn/__virtual__/copy-webpack-plugin-virtual-1a86820edc/0/cache/copy-webpack-plugin-npm-10.0.0-cbf3ed64fd-70652af613.zip/node_modules/copy-webpack-plugin/dist/index.js
Did you mean to import globby-npm-12.0.2-6be2a4aac6-f474ced866.zip/node_modules/globby/index.js?
    at new NodeError (node:internal/errors:371:5)
    at packageResolve (node:internal/modules/esm/resolve:864:9)
    at moduleResolve (node:internal/modules/esm/resolve:910:18)
    at defaultResolve (node:internal/modules/esm/resolve:1005:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:475:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:245:18)
    at ESMLoader.import (node:internal/modules/esm/loader:326:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1036:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:437:21)
    at importModuleDynamically (node:vm:381:46)
caused by plugins in Compilation.hooks.processAssets
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'globby' imported from /Users/moquette/Downloads/repo-copy-webpack-plugin-pnp-main/.yarn/__virtual__/copy-webpack-plugin-virtual-1a86820edc/0/cache/copy-webpack-plugin-npm-10.0.0-cbf3ed64fd-70652af613.zip/node_modules/copy-webpack-plugin/dist/index.js
Did you mean to import globby-npm-12.0.2-6be2a4aac6-f474ced866.zip/node_modules/globby/index.js?
    at new NodeError (node:internal/errors:371:5)
    at packageResolve (node:internal/modules/esm/resolve:864:9)
    at moduleResolve (node:internal/modules/esm/resolve:910:18)
    at defaultResolve (node:internal/modules/esm/resolve:1005:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:475:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:245:18)
    at ESMLoader.import (node:internal/modules/esm/loader:326:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1036:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:437:21)
    at importModuleDynamically (node:vm:381:46)

[ ~/Downloads/repo-copy-webpack-plugin-pnp-main/ ] $ 

Thank you!
Joaquin

**Comment by FeeLeeeD** [comment]
@moquette, you may try updating yarn version to 3.2.0 (https://github.com/webpack-contrib/copy-webpack-plugin/issues/643)
